name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install and build client
      run: |
        cd client
        npm install --legacy-peer-deps
        npm run build
        
    - name: Install server dependencies
      run: |
        cd server
        npm install --production
        
    - name: Run tests before deployment
      run: |
        cd server
        npm test
        
    - name: Deploy to staging (on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here
        
    - name: Deploy to production (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
        
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: |
          client/build/
          server/
          !server/node_modules/
          !server/test/